"""initial

Revision ID: 7770e39b21d6
Revises: 
Create Date: 2026-05-19 23:44:06.551371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7770e39b21d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audio_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('vocal_sep_model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_id'), 'audio_assets', ['id'], unique=False)
    op.create_index(op.f('ix_audio_assets_user_id'), 'audio_assets', ['user_id'], unique=False)
    op.create_table('style_vectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=255), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('style_extract_model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index(op.f('ix_style_vectors_id'), 'style_vectors', ['id'], unique=False)
    op.create_index(op.f('ix_style_vectors_user_id'), 'style_vectors', ['user_id'], unique=False)
    op.create_table('voice_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_audio_id', sa.Integer(), nullable=True),
    sa.Column('checkpoint_path', sa.String(length=512), nullable=True),
    sa.Column('config_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('quality_tier', sa.String(length=20), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_audio_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_models_id'), 'voice_models', ['id'], unique=False)
    op.create_index(op.f('ix_voice_models_user_id'), 'voice_models', ['user_id'], unique=False)
    op.create_table('generated_music',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('music_gen_model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vector_id'], ['style_vectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_music_id'), 'generated_music', ['id'], unique=False)
    op.create_index(op.f('ix_generated_music_user_id'), 'generated_music', ['user_id'], unique=False)
    op.create_table('vocal_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voice_model_id', sa.Integer(), nullable=False),
    sa.Column('reference_audio_id', sa.Integer(), nullable=True),
    sa.Column('output_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reference_audio_id'], ['audio_assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_model_id'], ['voice_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocal_generations_id'), 'vocal_generations', ['id'], unique=False)
    op.create_index(op.f('ix_vocal_generations_user_id'), 'vocal_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocal_generations_user_id'), table_name='vocal_generations')
    op.drop_index(op.f('ix_vocal_generations_id'), table_name='vocal_generations')
    op.drop_table('vocal_generations')
    op.drop_index(op.f('ix_generated_music_user_id'), table_name='generated_music')
    op.drop_index(op.f('ix_generated_music_id'), table_name='generated_music')
    op.drop_table('generated_music')
    op.drop_index(op.f('ix_voice_models_user_id'), table_name='voice_models')
    op.drop_index(op.f('ix_voice_models_id'), table_name='voice_models')
    op.drop_table('voice_models')
    op.drop_index(op.f('ix_style_vectors_user_id'), table_name='style_vectors')
    op.drop_index(op.f('ix_style_vectors_id'), table_name='style_vectors')
    op.drop_table('style_vectors')
    op.drop_index(op.f('ix_audio_assets_user_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
