import type { ModelCatalog, ModelInfo } from "@/types";

export const DEFAULT_VOCAL_SEPARATION_MODELS: ModelInfo[] = [
  {
    key: "demucs_htdemucs",
    display_name: "Demucs HT",
    description: "Hybrid Transformer 6-source separation，最高品质人声分离，支持四轨分离",
    vram_gb: 6.5,
    quality: "最高",
    speed: "较慢",
    pros: ["业界最佳分离品质", "支持人声/鼓/贝斯/其他四轨分离", "对中文歌曲优化良好"],
    cons: ["处理速度较慢，单曲约 2-3 分钟", "需要 6.5GB+ VRAM", "CPU 模式几乎不可用"],
  },
  {
    key: "demucs_mdx_extra",
    display_name: "Demucs MDX Extra",
    description: "MDX 训练变体，额外数据增强，人声隔离效果出色",
    vram_gb: 5.0,
    quality: "很高",
    speed: "中等",
    pros: ["优秀的人声隔离效果", "品质与速度均衡", "VRAM 需求适中"],
    cons: ["不分离鼓组轨道", "极端嘈杂环境下表现下降"],
  },
  {
    key: "demucs_6s",
    display_name: "Demucs 6-Source",
    description: "完整 6 轨分离：人声/鼓/贝斯/其他/钢琴/吉他",
    vram_gb: 4.5,
    quality: "高",
    speed: "中等",
    pros: ["6 轨完整分离", "适合多轨混音需求", "VRAM 需求适中"],
    cons: ["分离速度较 MDX 慢", "钢琴/吉他分离精度有限"],
  },
  {
    key: "spleeter_2stems",
    display_name: "Spleeter 2-Stem",
    description: "Deezer 开源快速人声分离，U-Net 架构，极速处理",
    vram_gb: 1.5,
    quality: "中",
    speed: "很快",
    pros: ["极速处理，秒级完成", "CPU 可流畅运行", "资源占用极低"],
    cons: ["分离精度低于 Demucs", "仅支持人声/伴奏双轨"],
  },
  {
    key: "spleeter_5stems",
    display_name: "Spleeter 5-Stem",
    description: "5 轨分离版本：人声/鼓/贝斯/钢琴/其他，多轨提取",
    vram_gb: 2.0,
    quality: "中高",
    speed: "快",
    pros: ["5 轨多乐器分离", "速度与品质平衡", "CPU 可运行"],
    cons: ["分离精度不如 Demucs", "不支持中文歌曲特化"],
  },
];

export const DEFAULT_STYLE_EXTRACTION_MODELS: ModelInfo[] = [
  {
    key: "clap_laion",
    display_name: "CLAP LAION",
    description: "LAION 社区训练的对比语言-音频预训练模型，512 维嵌入，通用音乐理解力强",
    vram_gb: 1.2,
    quality: "高",
    speed: "快",
    embedding_dim: 512,
    pros: ["通用音乐理解能力最强", "512 维高维度风格嵌入", "支持中英文描述匹配", "VRAM 需求低 (1.2GB)"],
    cons: ["对细分电子流派区分度有限"],
  },
  {
    key: "clap_msclap",
    display_name: "CLAP MS-CLAP",
    description: "Microsoft CLAP 微调版，1024 维嵌入，音乐流派识别更精准",
    vram_gb: 1.5,
    quality: "很高",
    speed: "中等",
    embedding_dim: 1024,
    pros: ["1024 维更丰富嵌入", "流行/摇滚音乐分析精准", "流派判别力更强"],
    cons: ["推理速度略慢于 LAION 版", "VRAM 需求稍高"],
  },
  {
    key: "clap_htsat",
    display_name: "CLAP HTSAT-Huge",
    description: "最大 CLAP 变体，最高品质音频理解，512 维嵌入",
    vram_gb: 3.0,
    quality: "最高",
    speed: "较慢",
    embedding_dim: 512,
    pros: ["最高品质音频理解", "对复杂音乐结构感知强", "512 维高质量嵌入"],
    cons: ["VRAM 需求较高 (3GB)", "加载和推理速度较慢"],
  },
  {
    key: "encodec_6kbps",
    display_name: "EnCodec 6kbps",
    description: "Meta 神经音频编解码器，128 维紧凑潜码，极速轻量",
    vram_gb: 0.8,
    quality: "中高",
    speed: "很快",
    embedding_dim: 128,
    pros: ["极速提取，秒级完成", "VRAM 极低 (0.8GB)", "CPU 友好，适合低配设备"],
    cons: ["嵌入维度低 (128D)", "风格细节捕捉有限", "风格迁移效果一般"],
  },
];

export const DEFAULT_MUSIC_GENERATION_MODELS: ModelInfo[] = [
  {
    key: "musicgen_small",
    display_name: "MusicGen Small",
    description: "300M 参数轻量版，极速生成，适合快速灵感捕捉",
    vram_gb: 2.5,
    quality: "良好",
    speed: "很快",
    pros: ["生成速度最快，约 30 秒/曲", "低 VRAM 友好 (2.5GB)", "适合快速灵感迭代"],
    cons: ["音质细节不足", "复杂提示理解有限", "低频丰满度不足"],
  },
  {
    key: "musicgen_medium",
    display_name: "MusicGen Medium",
    description: "1.5B 参数，品质与速度最佳平衡，推荐主力使用",
    vram_gb: 5.0,
    quality: "高",
    speed: "中等",
    pros: ["音质与速度均衡", "风格跟随准确度高", "VRAM 需求适中 (5GB)"],
    cons: ["长曲目 (>2min) 结构松散", "极端风格组合可能退化"],
  },
  {
    key: "musicgen_large",
    display_name: "MusicGen Large",
    description: "3.3B 参数最强版本，输出品质接近专业制作",
    vram_gb: 8.0,
    quality: "最高",
    speed: "较慢",
    pros: ["最高音质输出，接近专业水准", "复杂音乐结构理解力强", "多风格/多乐器融合自然"],
    cons: ["生成速度较慢，单曲约 3-5 分钟", "需要 8GB+ VRAM", "不支持实时预览"],
  },
  {
    key: "musicgen_melody",
    display_name: "MusicGen Melody",
    description: "1.5B 参数旋律条件版，跟随参考音频的和声结构生成",
    vram_gb: 5.5,
    quality: "很高",
    speed: "中等",
    pros: ["跟随参考音频和声结构", "旋律连贯性更好", "适合有明确旋律参考的创作"],
    cons: ["需要参考音频输入", "VRAM 需求较 Medium 略高"],
  },
  {
    key: "audioldm2",
    display_name: "AudioLDM 2",
    description: "潜在扩散音频生成模型，文本理解力突出，创意风格多样",
    vram_gb: 6.0,
    quality: "高",
    speed: "较慢",
    pros: ["文本语义理解力最强", "创意/实验风格多样", "支持音效与环境声生成"],
    cons: ["音质一致性不稳定", "生成时间较长 (2-4 分钟)", "对音乐结构把控较弱"],
  },
];

export const DEFAULT_MODEL_CATALOG: ModelCatalog = {
  vocal_separation: DEFAULT_VOCAL_SEPARATION_MODELS,
  style_extraction: DEFAULT_STYLE_EXTRACTION_MODELS,
  music_generation: DEFAULT_MUSIC_GENERATION_MODELS,
};
